### ISSUE TITLE
MMS Roadmap/Wishlist

### ISSUE THREAD

**Issue by ishmaelen** [mediamonkeyserver/mms#13]
Great work so far! - Seems to be running like a charm (tested on Win10&Debian9).

Is there a roadmap for MMS somewhere? Is the intention to eventually do stuff like my wishlist below?

1) Can you please add the same views as in MM4/5 Desktop incl. the loved column browser? 
2) Playlist
3) Google search artwork (manual per album - nothing fancy) and save
4) Support for adding and syncing podcasts
5) It would also be nice to see stuff like "Recently Added", "Starred", "Top Rated", "Most Played" etc.

Finally it seems we can scrap *sonic,ampache or whatever people use to play their collections from remote locations.

Thanks!

**Comment by jirihajek** [comment]
Thanks, nice to hear that!

We don't have any public MMS roadmap atm, but we are very interested in user's feedback and suggestions. Particularly the MMS forum https://www.mediamonkey.com/forum/viewforum.php?f=31 is a great place for any related discussion.

As for the wishlist:
1&2. The MMS Web UI isn't the top priority for us, as we prefer to work on MM5 and MMA as clients for MMS. That said, certainly also MMS UI will evolve, just a bit slowly. Unless more users contribute, since MMS is open-sourced... ;-)
3-5. These features either already are, or shortly will be, possible by cooperation of MMS and MM5 (i.e. MM5 doing the work and MMS being the backend serving data to clients). More autonomous mode, i.e. without the need for MM5 to do the work, is planned as well, but will need some time to complete.

Jiri

**Comment by ishmaelen** [comment]
Thanks for the feedback. I'll do a thread in the forums and close the issue.
